### ISSUE TITLE
[TASK] - vl-ui-upload laten customizen dmv. slots

### ISSUE THREAD

**Issue by stefanborghys** [milieuinfo/webcomponent-vl-ui-upload#148]
**Beschrijving**
Prozaberichten toelaten dmv. slots in de vl-ui-upload.

**Extra info**
Zie: https://www.milieuinfo.be/jira/browse/UIG-1188

**Comment by coemans** [comment]
@stefanborghys best in de toekomst ook het issue linken aan de PR zodat het automatisch afgesloten wordt bij een merge.
