### ISSUE TITLE
[BUG] - drop van bestand triggered geen input event

### ISSUE THREAD

**Issue by FreekRombauts** [milieuinfo/webcomponent-vl-ui-upload#154]
**Omschrijf het probleem**
Een input veld genereert normaal een input event als de value ervan veranderd. Selecteren van een bestand via de filepicker genereert dit input event. Een bestand droppen, wat visueel een identiek resultaat geeft, genereert dit input event niet.

**Hoe te reproduceren**
vl-upload component gebruiken met een input event listener. Event listener wordt getriggered bij file selectie via dialog, maar niet bij file selectie via drop.

**Gewenst gedrag**
input event wordt ook afgevuurd bij een drop.

**Comment by coemans** [comment]
Probleem zit in DropzoneJS, cfr. [voorbeeld](https://www.dropzonejs.com/examples/simple.html). In afwachting dat er bij DropzoneJS opgelost wordt, kan het `change` event gebruikt worden.

**Comment by kevcraey** [comment]
https://www.milieuinfo.be/jira/browse/UIG-2213
