### ISSUE TITLE
[BUG] - Remove file laat foutmelding staan

### ISSUE THREAD

**Issue by cambiph** [milieuinfo/webcomponent-vl-ui-upload#27]
**Korte omschrijving**
DropzoneJS gaat niet hervalideren op max files indien je een bestand verwijdert: https://gitlab.com/meno/dropzone/issues/179.

**Comment by cambiph** [comment]
Sander Bylemans added a comment - 09/Jul/19 11:12 AM

>Mogelijke workaround is om de styling aan te passen om de dropzone te verbergen wanneer max-files bereikt is. DropzoneJS zet daar dan zelf al een klasse op.

**Comment by coemans** [comment]
Er werd een issue/request aangemaakt bij Dropzone. Ik stel voor om de verwarring weg te werken door de foutmelding "Je kan maximaal 2 file(s) uploaden" te vervangen door "Dit bestand werd niet verwerkt omdat er maximaal 2 bestanden opgeladen kunnen worden".

Afhankelijk van de feedback/actie van Dropzone kan dit later aangepast/bijgestuurd worden.

**Comment by coemans** [comment]
Offline besproken met @SBylemans. Akkoord met tekstwijziging, maar er zal ook een selector voorzien worden voor het upload input element.

Er werd gevraagd om het upload input element te verbergen wanneer het maximum aantal uploads bereikt is, maar deze wijziging is niet gewenst voor andere afnemers. Er zal daarom een uitbreiding voorzien worden zodat het upload input element opgevraagd kan worden op vl-upload niveau. Hierdoor wordt het mogelijk om applicatief interactie te voorzien met het input element.
