### ISSUE TITLE
[BUG] - Webuniversum: addedfiles event van dropzone gebeurt te vroeg

### ISSUE THREAD

**Issue by cambiph** [milieuinfo/webcomponent-vl-ui-upload#28]
**Korte omschrijving**
De 'addedfiles' event van dropzonejs wordt te vroeg gefired waardoor de file nog niet is toegevoegd aan dropzone.files property. https://gitlab.com/meno/dropzone/issues/87

Workaround: 

          dropzone$$1.on('addedfiles', function () {
            setTimeout(() => vl.util.triggerEvent(element, 'vl.upload.hook.fileChange'));
          });

**Comment by coemans** [comment]
Issue is ondertussen verdwenen doordat dropzone verplaatst werd van GitLab naar GitHub. @driesva jullie hebben aangegeven hier last van te ondervinden. Is het mogelijk om hiervoor een test toe te voegen of te beschrijven hoe het probleem gereproduceerd kan worden zodat er gericht naar een oplossing gezocht kan worden?

**Comment by driesva** [comment]
@coemans zegt mij niet onmiddellijk iets... Staat ook bij Phoenix op input pagina. Zie o.a. ook UIG-894

**Comment by coemans** [comment]
Blijkbaar iets verkeerd gelopen in communicatie tot bij mij dan. Mijn vraag is dan van toepassing voor Phoenix.

**Comment by FreekRombauts** [comment]
@coemans , ik heb een poging gedaan te reconstrueren waar de oorspronkelijke bug vandaan kwam. Dit is hetgene dat ik tegengekomen ben.

Gegeven een upload component en volgende js: 
```    
  this._upload.on('addedfiles', (files) => {
      console.log('from addedfiles');
      console.log(files);
      console.log(this._upload.acceptedFiles);
      console.log(this._upload.files);
      console.log(this._upload.value);
    });

    this._upload.on('vl.upload.hook.fileChange', () => {
      console.log('from fileChange');
      console.log(this._upload.acceptedFiles);
      console.log(this._upload.files);
      console.log(this._upload.value);
    });
```

Je zou verwachten dat de gelogde lijst van bestanden telkens hetzelfde is. Bij het toevoegen van een bestand via een file-upload dialog is dat ook het geval:

```
[Log] from addedfiles
[Log] FileList {0: File, length: 1, item: function}
[Log] [File] (1)
[Log] [File] (1)
[Log] [File] (1)
[Log] from fileChange
[Log] [File] (1)
[Log] [File] (1)
[Log] [File] (1)
```

Maar bij drag-drop van een bestand niet. Dan is het bestand bij de addedfiles event alleen zichtbaar in de parameter, en niet in de component values.

```
[Log] from addedfiles
[Log] [File] (1)
[Log] [] (0)
[Log] [] (0)
[Log] undefined
[Log] from fileChange
[Log] [File] (1)
[Log] [File] (1)
[Log] [File] (1)
```

Naast het ontbreken van het gedropte bestand in acceptedFiles, files, en value zijn er nog 2 andere verschillen:
* Bij drop is de parameter voor de addedFiles event een array van File ipv een FileList object
* Bij drop is de value property undefined ipv een lege lijst

Wat betreft die issue 87 op gitlab, die vind ik inderdaad niet meer terug. Wel nog de merge commit die de issue zou moeten oplossen (13 feb 2020 - https://gitlab.com/meno/dropzone/-/merge_requests/37 ). Dropzone versie in de upload component is op eerste zicht 5.5.1, wat te oud is voor die fix. Minstens 5.6.1 of 5.7.0 nodig denk ik.

Lijkt mij op eerste zicht dus de moeite waarde om eens de laatste dropzone versie in de component op te nemen. Mogelijks is het daarmee opgelost.

**Comment by coemans** [comment]
PR werd centraal aangemaakt. Afwachten op review/merge/release om intern verder te verwerken.
