### ISSUE TITLE
[Task] - Broken build

### ISSUE THREAD

**Issue by Pieter-Beckers** [milieuinfo/webcomponent-vl-ui-upload#30]
Renovate heeft iets op een of andere manier de package-lock.json niet goed gebouwd en hierdoor faalt de build.

"npm install" geeft foutmeldingen bij het parsen van de JSON

Zie ook interne bamboo build: https://www.milieuinfo.be/bamboo/browse/WEBCOM-VLUIUPLOAD

**Comment by Pieter-Beckers** [comment]
Zie ook PR: https://github.com/milieuinfo/webcomponent-vl-ui-upload/pull/31

**Comment by coemans** [comment]
@cambiph bekijk jij dit probleem verder? Ik heb alvast PR goedgekeurd.

Op basis van dit ticket lijkt er ook nog iets mis te zijn met de issue templates, toch voor deze component?

**Comment by cambiph** [comment]
PR heeft het gefixed.
Issue template is in orde nu, heb de laatste versie van de util laten lopen en gemerged.
