### ISSUE TITLE
[FEATURE] - De standaard tekst aanpassen

### ISSUE THREAD

**Issue by ZhaodiFengVlaanderen** [milieuinfo/webcomponent-vl-ui-upload#47]
**Wat moet er gebeuren**
De vl-ui-upload heeft een hardcoded tekst "Bijlage toevoegen" en is niet aanpasbare. Zo graag dit tekst  een parameter worden.

**Comment by coemans** [comment]
@ZhaodiFengVlaanderen indien PR goedgekeurd wordt, zal bij de volgende huisstijl upgrade dit issue opgelost en gesloten worden. Als jullie de feature vroeger nodig hebben, kan de code op ons niveau vervroegd toegepast worden. Graag dan een seintje.
