### ISSUE TITLE
[FEATURE] - Disable van upload

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-upload#61]
**Wat moet er gebeuren**
Het zou mogelijk moeten zijn om de volledige vl-ui-upload te kunnen disablen. Bijvoorbeeld als je iets oplaadt en de upload is nog lopende, wil je interactie met de component kunnen afzetten. 

**Extra info**
Huidige workaround (maar geen visuele impact):
`this._fileSelector.shadowRoot.querySelectorAll("input, button")
      .forEach(component => component.removeAttribute("disabled"));`

Merk op dat de onderliggende dropzone disable/enable functionaliteit heeft, maar die kan je niet aanroepen terwijl upload nog lopend is want dat resulteert in een fout.

**Comment by coemans** [comment]
PR aangemaakt bij AIV met disable/enable uitbreiding.

**Comment by coemans** [comment]
@driesva indien PR goedgekeurd wordt, zal bij de volgende huisstijl upgrade dit issue opgelost en gesloten worden. Als jullie de feature vroeger nodig hebben, kan de code op ons niveau vervroegd toegepast worden. Graag dan een seintje.

**Comment by driesva** [comment]
Voorlopig nog niet nodig. Pas als we VHRM terug oppikken (kan pas als map er is)
