### ISSUE TITLE
[FEATURE] - Timeout behandelen

### ISSUE THREAD

**Issue by ZhaodiFengVlaanderen** [milieuinfo/webcomponent-vl-ui-upload#68]
**Wat moet er gebeuren**

Dropzone heeft een default upload timeout van 30 sec. En er is ook geen visuele fout melding na de timeout.

**Comment by coemans** [comment]
Ondertussen staat de default timeout uitgeschakeld waardoor er door Dropzone zelf geen timeout meer zal optreden.
