### ISSUE TITLE
[BUG] - De fileType variabele wordt niet vertaald naar het juiste bestandstype

### ISSUE THREAD

**Issue by cambiph** [milieuinfo/webcomponent-vl-ui-upload#84]
**Omschrijf het probleem**
Een duidelijke en korte uitleg over het probleem.

**Hoe te reproduceren**
Check de demo-pagina

**Screenshots**
![image-2020-02-17-11-06-49-520](https://user-images.githubusercontent.com/1628243/75774832-15575300-5d51-11ea-9fff-558539af6500.png)

**Comment by coemans** [comment]
Het moet `filetype` zijn i.p.v. `fileType`. Probleem beperkt zich tot demo pagina en werd opgelost in PR #120 en zal toegevoegd worden aan de eerstvolgende release.
