### ISSUE TITLE
[BUG] - Error message bij max file size verkeerd

### ISSUE THREAD

**Issue by Pieter-Beckers** [milieuinfo/webcomponent-vl-ui-upload#99]
**Omschrijf het probleem**
Max file size error message is verkeerd. De grootte is hier niet correct. Zie screenshot. De functionaliteit werkt wel correct: de error message komt enkel als de file te groot is.

Ook foutje in documentatie: (20000000 = 2MB)

**Hoe te reproduceren**
Een bestand opladen dat groter is dan de max-size.

**Gewenst gedrag**
De correcte max file size wordt getoond
**Screenshots**
![image](https://user-images.githubusercontent.com/28813026/81391950-3c018380-911e-11ea-880c-d7173e0ff476.png)

**Extra info**
Ook in https://overheid.vlaanderen.be/webuniversum/v3/documentation/forms/vl-ui-upload

**Comment by coemans** [comment]
Problem is niet meer reproduceerbaar, werd vermoedelijk ondertussen opgelost.

<img width="2560" alt="bytes" src="https://user-images.githubusercontent.com/11139249/89503546-fd37a400-d7c6-11ea-983f-eb50578e7086.png">

**Comment by coemans** [comment]
Wel nog reproduceerbaar bij 2 MB.

<img width="2560" alt="2mb" src="https://user-images.githubusercontent.com/11139249/89505842-87cdd280-d7ca-11ea-8571-86d23f68feda.png">

**Comment by coemans** [comment]
Na de huisstijl upgrade, deed het probleem zich nog voor. Ik heb een PR toegevoegd om het achterliggend probleem op te lossen en tijdelijk in onze code een fix voorzien.
